---

- name: Copy binary
  copy:
    src: "{{GAIACLI_BINARY}}"
    dest: /usr/bin/wasmcli
    mode: 0755
  notify: restart wasmcli

- name: Copy service
  template:
    src: wasmcli.service.j2
    dest: /etc/systemd/system/wasmcli.service
  notify: systemctl

