---

- name: Stop service
  service: name=wasmd state=stopped

- name: Delete files
  file: "path={{item}} state=absent"
  with_items:
  - /usr/bin/wasmd
  - /home/wasmd/.wasmd
  - /home/wasmd/.wasmcli

